// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package furrow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	RequestID            string      `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Image                string      `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	Cmd                  []string    `protobuf:"bytes,3,rep,name=Cmd,proto3" json:"Cmd,omitempty"`
	Env                  []string    `protobuf:"bytes,4,rep,name=Env,proto3" json:"Env,omitempty"`
	Notify               string      `protobuf:"bytes,5,opt,name=Notify,proto3" json:"Notify,omitempty"`
	Volumes              *Job_Volume `protobuf:"bytes,7,opt,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *Job) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Job) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Job) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Job) GetNotify() string {
	if m != nil {
		return m.Notify
	}
	return ""
}

func (m *Job) GetVolumes() *Job_Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Job_Volume struct {
	In                   string   `protobuf:"bytes,1,opt,name=In,proto3" json:"In,omitempty"`
	Out                  string   `protobuf:"bytes,2,opt,name=Out,proto3" json:"Out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job_Volume) Reset()         { *m = Job_Volume{} }
func (m *Job_Volume) String() string { return proto.CompactTextString(m) }
func (*Job_Volume) ProtoMessage()    {}
func (*Job_Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0, 0}
}

func (m *Job_Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job_Volume.Unmarshal(m, b)
}
func (m *Job_Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job_Volume.Marshal(b, m, deterministic)
}
func (m *Job_Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job_Volume.Merge(m, src)
}
func (m *Job_Volume) XXX_Size() int {
	return xxx_messageInfo_Job_Volume.Size(m)
}
func (m *Job_Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Job_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Job_Volume proto.InternalMessageInfo

func (m *Job_Volume) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

func (m *Job_Volume) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

type Notification struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Notification) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "furrow.Job")
	proto.RegisterType((*Job_Volume)(nil), "furrow.Job.Volume")
	proto.RegisterType((*Notification)(nil), "furrow.Notification")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xe9, 0x9f, 0xed, 0xd2, 0x51, 0x44, 0x06, 0x91, 0x20, 0x1e, 0xca, 0x9e, 0x8a, 0x48,
	0x0e, 0xeb, 0x47, 0xb0, 0x7b, 0xc8, 0x1e, 0x14, 0x72, 0xf0, 0x9e, 0x68, 0x56, 0x2a, 0x36, 0xa3,
	0xdd, 0xa4, 0xe2, 0xa7, 0xf4, 0x2b, 0x49, 0xfe, 0x88, 0xb7, 0x37, 0xbf, 0xc9, 0xe3, 0xbd, 0x0c,
	0xb4, 0x6f, 0xa4, 0xf9, 0xc7, 0x4c, 0x8e, 0xb0, 0x39, 0xf8, 0x79, 0xa6, 0xaf, 0xcd, 0x4f, 0x01,
	0xd5, 0x9e, 0x34, 0x5e, 0x43, 0x2b, 0xcd, 0xa7, 0x37, 0x47, 0x27, 0x06, 0x56, 0x74, 0x45, 0xdf,
	0xca, 0x7f, 0x80, 0x17, 0xb0, 0x12, 0x93, 0x7a, 0x35, 0xac, 0x8c, 0x9b, 0x34, 0xe0, 0x39, 0x54,
	0xf7, 0xd3, 0x0b, 0xab, 0xba, 0xaa, 0x6f, 0x65, 0x90, 0x81, 0xec, 0xec, 0xc2, 0xea, 0x44, 0x76,
	0x76, 0xc1, 0x4b, 0x68, 0x1e, 0xc8, 0x8d, 0x87, 0x6f, 0xb6, 0x8a, 0xd6, 0x3c, 0xe1, 0x2d, 0xac,
	0x17, 0x7a, 0xf7, 0x93, 0x39, 0xb2, 0x75, 0x57, 0xf4, 0x27, 0x5b, 0xe4, 0xa9, 0x11, 0xdf, 0x93,
	0xe6, 0x4f, 0x71, 0x25, 0xff, 0x9e, 0x5c, 0xdd, 0x40, 0x93, 0x10, 0x9e, 0x41, 0x29, 0x6c, 0x2e,
	0x58, 0x0a, 0x1b, 0x12, 0x1f, 0xbd, 0xcb, 0xbd, 0x82, 0xdc, 0x6c, 0xe1, 0x34, 0x66, 0x8c, 0xcf,
	0xca, 0x8d, 0x64, 0xa3, 0x23, 0x7d, 0xa9, 0x96, 0xa5, 0x18, 0x10, 0xa1, 0x1e, 0x94, 0x53, 0xd9,
	0x12, 0xb5, 0x6e, 0xe2, 0x51, 0xee, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x0b, 0x98, 0xfa,
	0x21, 0x01, 0x00, 0x00,
}
